name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build --parallel

      - name: Run tests
        run: ./cmake-build-debug/tests/RealtimeModelTests
